// Copyright (c) 2025-2026 The Pearl Research Labs
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package btcutil_test

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"net"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/pearl-research-labs/pearl/node/btcutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestNewTLSCertPair ensures the NewTLSCertPair function works as expected.
func TestNewTLSCertPair(t *testing.T) {
	// Certs don't support sub-second precision, so truncate it now to
	// ensure the checks later don't fail due to nanosecond precision
	// differences.
	validUntil := time.Unix(time.Now().Add(10*365*24*time.Hour).Unix(), 0)
	org := "test autogenerated cert"
	extraHosts := []string{"testtlscert.bogus", "localhost", "127.0.0.1"}
	cert, key, err := btcutil.NewTLSCertPair(org, validUntil, extraHosts)
	require.NoError(t, err)

	// The returned PEM cert and key must decode and parse.
	pemCert, _ := pem.Decode(cert)
	require.NotNil(t, pemCert, "could not decode certificate PEM")
	pemKey, _ := pem.Decode(key)
	require.NotNil(t, pemKey, "could not decode key PEM")

	_, err = x509.ParsePKCS8PrivateKey(pemKey.Bytes)
	assert.NoError(t, err, "key is not a valid PKCS#8 private key")

	x509Cert, err := x509.ParseCertificate(pemCert.Bytes)
	require.NoError(t, err)

	// The subject organization matches.
	assert.Equal(t, []string{org}, x509Cert.Subject.Organization)

	// NotAfter matches the requested validity (compare instants, since the
	// parsed value's location may differ).
	assert.Truef(t, x509Cert.NotAfter.Equal(validUntil),
		"NotAfter = %v, want %v", x509Cert.NotAfter, validUntil)

	// All requested extra hosts verify.
	for _, host := range extraHosts {
		assert.NoErrorf(t, x509Cert.VerifyHostname(host),
			"failed to verify extra host %q", host)
	}

	// The Common Name is also the first SAN DNS name.
	require.NotEmpty(t, x509Cert.DNSNames)
	assert.Equal(t, x509Cert.Subject.CommonName, x509Cert.DNSNames[0],
		"common name does not match first SAN")

	// There are no duplicate hosts or IPs.
	hostCounts := make(map[string]int)
	for _, host := range x509Cert.DNSNames {
		hostCounts[host]++
	}
	for host, count := range hostCounts {
		assert.Equalf(t, 1, count, "host %q appears %d times", host, count)
	}
	ipCounts := make(map[string]int)
	for _, ip := range x509Cert.IPAddresses {
		ipCounts[string(ip)]++
	}
	for ipStr, count := range ipCounts {
		assert.Equalf(t, 1, count, "ip %s appears %d times", net.IP(ipStr), count)
	}

	// The cert can be used for the intended purposes.
	assert.True(t, x509Cert.IsCA, "cert is not a certificate authority")
	assert.NotZero(t, x509Cert.KeyUsage&x509.KeyUsageKeyEncipherment,
		"cert can't be used for key encipherment")
	assert.NotZero(t, x509Cert.KeyUsage&x509.KeyUsageDigitalSignature,
		"cert can't be used for digital signatures")
	assert.NotZero(t, x509Cert.KeyUsage&x509.KeyUsageCertSign,
		"cert can't be used for signing other certs")
	assert.True(t, x509Cert.BasicConstraintsValid,
		"cert does not have valid basic constraints")
}

// TestWriteTLSCertPair ensures WriteTLSCertPair creates parent directories,
// writes a loadable cert/key pair with the correct file modes, and omits the
// key when writeKey is false.
func TestWriteTLSCertPair(t *testing.T) {
	validUntil := time.Now().Add(time.Hour)

	t.Run("writes a loadable pair with strict perms", func(t *testing.T) {
		dir := t.TempDir()
		certFile := filepath.Join(dir, "sub", "rpc.cert")
		keyFile := filepath.Join(dir, "sub", "rpc.key")

		keyPair, err := btcutil.WriteTLSCertPair(certFile, keyFile, "test",
			validUntil, nil, true)
		require.NoError(t, err)
		assert.NotEmpty(t, keyPair.Certificate)

		_, err = tls.LoadX509KeyPair(certFile, keyFile)
		assert.NoError(t, err)

		// File mode bits are not meaningful on Windows.
		if runtime.GOOS != "windows" {
			assertFileMode(t, certFile, 0644) // public
			assertFileMode(t, keyFile, 0600)  // owner-only
		}
	})

	t.Run("tightens an existing loose key to 0600", func(t *testing.T) {
		if runtime.GOOS == "windows" {
			t.Skip("file mode bits are not meaningful on Windows")
		}
		dir := t.TempDir()
		certFile := filepath.Join(dir, "rpc.cert")
		keyFile := filepath.Join(dir, "rpc.key")
		require.NoError(t, os.WriteFile(keyFile, []byte("stale"), 0644))

		_, err := btcutil.WriteTLSCertPair(certFile, keyFile, "test",
			validUntil, nil, true)
		require.NoError(t, err)
		assertFileMode(t, keyFile, 0600)
	})

	t.Run("one-time key is not persisted", func(t *testing.T) {
		dir := t.TempDir()
		certFile := filepath.Join(dir, "rpc.cert")
		keyFile := filepath.Join(dir, "rpc.key")

		_, err := btcutil.WriteTLSCertPair(certFile, keyFile, "test",
			validUntil, nil, false)
		require.NoError(t, err)
		assert.FileExists(t, certFile)
		assert.NoFileExists(t, keyFile)
	})
}

// TestWriteTLSCertPairCleansUpOnKeyFailure ensures that if the private key
// cannot be persisted -- whether the stale key cannot be removed or the new
// key cannot be written -- the freshly written certificate is cleaned up
// rather than left mismatched with (or orphaned without) a key.
func TestWriteTLSCertPairCleansUpOnKeyFailure(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("directory write permissions are not meaningful on Windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("read-only directory permissions do not apply to root")
	}

	validUntil := time.Now().Add(time.Hour)

	// Each case makes the key's directory read-only so the key cannot be
	// persisted, while the cert's directory stays writable. With a stale
	// key present, os.Remove(keyFile) fails; without one, os.Remove is a
	// no-op and os.WriteFile(keyFile) fails instead. Either way the cert
	// must be removed.
	run := func(t *testing.T, seedStaleKey bool) {
		dir := t.TempDir()
		certFile := filepath.Join(dir, "rpc.cert")

		keyDir := filepath.Join(dir, "keys")
		require.NoError(t, os.Mkdir(keyDir, 0700))
		keyFile := filepath.Join(keyDir, "rpc.key")
		if seedStaleKey {
			require.NoError(t, os.WriteFile(keyFile, []byte("stale"), 0600))
		}
		require.NoError(t, os.Chmod(keyDir, 0500))
		t.Cleanup(func() { _ = os.Chmod(keyDir, 0700) })

		_, err := btcutil.WriteTLSCertPair(certFile, keyFile, "test",
			validUntil, nil, true)
		require.Error(t, err)
		assert.NoFileExists(t, certFile,
			"cert must be removed when the key cannot be persisted")
	}

	t.Run("key removal fails", func(t *testing.T) { run(t, true) })
	t.Run("key write fails", func(t *testing.T) { run(t, false) })
}

func assertFileMode(t *testing.T, name string, want os.FileMode) {
	t.Helper()
	info, err := os.Stat(name)
	require.NoError(t, err)
	assert.Equal(t, want, info.Mode().Perm())
}
