//! V1-format ZK proofs.
//!
//! This module is a self-contained copy of the v1's circuit and API code,
//! used to verify proofs generated by the original (pre-MoE) STARK.
//! It is NOT used for new proof generation — only verification.

pub mod api;
pub mod circuit;
pub mod embedded_cache;

#[cfg(test)]
mod compat_test;

// Re-export the ensure_eq macro from the main crate for use within this module
pub use crate::ensure_eq;

use crate::v1::circuit::circuit_utils::CircuitCache;

/// Verify a V1 ZK proof.
///
/// Arguments:
/// - `block_header_bytes`: 76-byte serialized IncompleteBlockHeader
/// - `public_data`: 164-byte public data (V1 wire format)
/// - `proof_data`: proof blob (preamble + plonky2 proof)
/// - `cache`: pre-populated V1 circuit cache
/// - `nbits_override`: if Some, use this nbits instead of the header's
pub fn verify_v1(
    block_header_bytes: &[u8],
    public_data: &[u8],
    proof_data: &[u8],
    cache: &CircuitCache,
    nbits_override: Option<u32>,
) -> anyhow::Result<()> {
    use api::proof::{IncompleteBlockHeader, PublicProofParams, ZKProof};

    let block_header = IncompleteBlockHeader::from_bytes(block_header_bytes)?;

    let public_params = PublicProofParams::from_bytes(
        block_header,
        public_data.try_into().map_err(|_| {
            anyhow::anyhow!(
                "v1 public_data must be {} bytes, got {}",
                PublicProofParams::PUBLICDATA_SIZE,
                public_data.len()
            )
        })?,
    )?;

    let zk_proof = ZKProof::from_bytes(proof_data)?;

    api::verify::verify_block_cached_circuits_only(&public_params, &zk_proof, cache, nbits_override)
}
